# Site settings github
title: Abhishek Jaiswal
email: gateway2abhi@yahoo.co.in
description: > # this means to ignore newlines until "baseurl:"
 Personal-blog abhishek jaiswal software engineer kolkata acharya institute management sciences
 https://plus.google.com/+abhishekjaiswalabhishek/posts
 http://in.linkedin.com/pub/abhishek-jaiswal/3b/849/575
 .
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://abhishek-jaiswal.github.io" # the base hostname & protocol for your site
twitter_username: abhishek_jaisw
github_username: abhishek-jaiswal

# Build settings
markdown: redcarpet
redcarpet:
  input: GFM
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
